<select id="filterObor" name="filterObor" className="form-control">
  <option value=""></option>
  <option value="16">alergologie a klinická imunologie</option>
  <option value="107">algeziologie</option>
  <option value="17">anesteziologie a intenzivní medicína</option>
  <option value="1">angiologie</option>
  <option value="19">biomedicínská kybernetika</option>
  <option value="20">cévní chirurgie</option>
  <option value="21">čelistní ortopedie</option>
  <option value="22">dermatovenerologie</option>
  <option value="29">dětská a dorostová psychiatrie</option>
  <option value="23">dětská dermatovenerologie</option>
  <option value="111">dětská endokrinologie a diabetologie</option>
  <option value="2">dětská gastroenterologie a hepatologie</option>
  <option value="24">dětská gynekologie</option>
  <option value="25">dětská chirurgie</option>
  <option value="26">dětská kardiologie</option>
  <option value="3">dětská nefrologie</option>
  <option value="27">dětská neurologie</option>
  <option value="4">dětská onkologie a hematologie</option>
  <option value="28">dětská otorinolaryngologie</option>
  <option value="5">dětská pneumologie</option>
  <option value="6">dětská radiologie</option>
  <option value="7">dětská revmatologie</option>
  <option value="30">dětská stomatologie</option>
  <option value="31">dětská urologie</option>
  <option value="99">dětské lékařství</option>
  <option value="32">diabetologie</option>
  <option value="33">dorostové lékařství</option>
  <option value="34">endokrinologie</option>
  <option value="101">endokrinologie a diabetologie</option>
  <option value="35">epidemiologie</option>
  <option value="18">foniatrie</option>
  <option value="37">gastroenterologie</option>
  <option value="38">geriatrie</option>
  <option value="39">gerontopsychiatrie</option>
  <option value="40">gynekologie a porodnictví</option>
  <option value="117">gynekologie dětí a dospívajících</option>
  <option value="41">hematologie a transfuzní lékařství</option>
  <option value="78">hrudní chirurgie</option>
  <option value="42">hygiena a epidemiologie</option>
  <option value="43">hygiena dětí a dorostu</option>
  <option value="45">hygiena obecná a komunální</option>
  <option value="46">hygiena výživy a předmětů běžného užívání</option>
  <option value="47">hygiena záření</option>
  <option value="8">hyperbarická a letecká medicína</option>
  <option value="48">chirurgie</option>
  <option value="80">infekční lékařství</option>
  <option value="9">intenzivní medicína</option>
  <option value="119">intervenční kardiologie</option>
  <option value="10">intervenční radiologie</option>
  <option value="50">kardiochirurgie</option>
  <option value="51">kardiologie</option>
  <option value="52">klinická biochemie</option>
  <option value="53">klinická farmakologie</option>
  <option value="54">klinická onkologie</option>
  <option value="102">klinická osteologie</option>
  <option value="108">klinická výživa a intenzivní metabolická péče</option>
  <option value="109">koloproktologie</option>
  <option value="55">korektivní dermatologie</option>
  <option value="57">lékařská bakteriologie</option>
  <option value="58">lékařská genetika</option>
  <option value="59">lékařská mikrobiologie</option>
  <option value="60">lékařská parazitologie</option>
  <option value="120">lékařská psychoterapie</option>
  <option value="61">lékařská virologie</option>
  <option value="62">letecké lékařství</option>
  <option value="88">maxilofaciální chirurgie</option>
  <option value="103">medicína dlouhodobé péče</option>
  <option value="63">mikrobiologie</option>
  <option value="64">mikrobiologie životního prostředí</option>
  <option value="56">návykové nemoci</option>
  <option value="65">nefrologie</option>
  <option value="66">neonatologie</option>
  <option value="67">neurochirugie</option>
  <option value="68">neurologie</option>
  <option value="11">neuroradiologie</option>
  <option value="69">nukleární medicína</option>
  <option value="70">oftalmologie</option>
  <option value="104">onkogynekologie</option>
  <option value="110">onkochirurgie</option>
  <option value="112">onkourologie</option>
  <option value="71">ortopedická protetika</option>
  <option value="72">ortopedie a traumatologie pohybového ústrojí</option>
  <option value="73">otorinolaryngologie a chirurgie hlavy a krku</option>
  <option value="12">paliativní medicína</option>
  <option value="74">parodontologie</option>
  <option value="75">patologie</option>
  <option value="98">pediatrie</option>
  <option value="76">perinatologie</option>
  <option value="105">perinatologie a fetomaternální medicína</option>
  <option value="77">plastická chirurgie</option>
  <option value="93">pneumologie a ftizeologie</option>
  <option value="13">popáleninová medicína</option>
  <option value="79">posudkové lékařství</option>
  <option value="44">pracovní lékařství</option>
  <option value="100">praktické lékařství pro děti a dorost</option>
  <option value="81">psychiatrie</option>
  <option value="114">psychosomatika</option>
  <option value="83">radiační onkologie</option>
  <option value="82">radiologie a zobrazovací metody</option>
  <option value="36">rehabilitační a fyzikální medicína</option>
  <option value="14">reprodukční medicína</option>
  <option value="84">revmatologie</option>
  <option value="85">sexuologie</option>
  <option value="87">soudní lékařství</option>
  <option value="115">spondylochirurgie</option>
  <option value="89">stomatologická protetika</option>
  <option value="90">stomatologie</option>
  <option value="91">tělovýchovné lékařství</option>
  <option value="92">traumatologie</option>
  <option value="94">tuberkulóza a respirační nemoci v dětském věku</option>
  <option value="118">úrazová chirurgie</option>
  <option value="95">urgentní medicína</option>
  <option value="106">urogynekologie</option>
  <option value="96">urologie</option>
  <option value="116">vaskulární intervenční radiologie</option>
  <option value="86">veřejné zdravotnictví</option>
  <option value="49">vnitřní lékařství</option>
  <option value="97">všeobecné praktické lékařství</option>
</select>;
